### PR TITLE
Fix enter key crashing everything

### PR DESCRIPTION
**Pull request by Fiffers**

### CODE REVIEW

**Comment by Fiffers** [comment]
[Here's a video demonstration](https://medal.tv/clips/46764578/d13371oIYhvZ)

**Comment by distritic** [comment]
Do we know exactly why this happens? Just curious.

**Comment by Fiffers** [comment]
I figured it was happening due to a standard HTML redirect function that occurs when you submit a form. So to test it out, I prevented that from happening (<el-form @keyup.enter.native>), which worked, then added a function to call the vuejs triggers to the inputs themselves (v-on:keyup.enter=) to make it appear to function normally.

**Comment by Fiffers** [comment]
[Here is where I figured it out](https://forum.vuejs.org/t/how-to-listen-for-an-enter-on-an-element-ui-form/11631)

**Comment by distritic** [comment]
I see, weird that it just broke. Thanks :)

**Pull request merged**
